# Generated by Django 3.1.3 on 2021-05-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.TextField(max_length=30)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.TextField(max_length=32),
        ),
        migrations.AddField(
            model_name='reservation',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.menu'),
        ),
    ]
