# Generated by Django 3.1.3 on 2021-05-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20210505_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='list_of_dishes',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='total_price',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
