# Generated by Django 3.1.3 on 2021-05-05 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20210505_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='dat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mysite.menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='relatives',
            field=models.ManyToManyField(related_name='_reservation_relatives_+', to='mysite.Reservation'),
        ),
    ]
