# Generated by Django 3.1.3 on 2021-05-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20210505_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='dat',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='relatives',
        ),
        migrations.AddField(
            model_name='reservation',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.menu'),
        ),
    ]
