# Generated by Django 3.1.3 on 2021-05-05 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20210505_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.reservation'),
        ),
    ]
