# Generated by Django 3.1.3 on 2021-05-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20210505_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
