# Generated by Django 3.1.3 on 2021-05-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
