# Generated by Django 3.1.3 on 2021-05-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.TextField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='orders',
            field=models.ManyToManyField(to='mysite.Order'),
        ),
    ]
