# Generated by Django 4.1.2 on 2023-11-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20210520_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
                ('firstnameAES', models.CharField(max_length=75)),
                ('usernameRSA', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'web_member',
            },
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='orders',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
